[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "datamgmt"
version = "0.1.0"
authors = [
  { name="Victor Rodriguez", email="victor.a.dicecco@gmail.com" },
]
description = "Shared financial analysis and API utilities"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiohttp",
    "nest_asyncio", 
    "pandas",
    "sqlalchemy", 
    "sqlite3", 
    "psycopg2-binary", 
    "greenlet==3.1.1"
    "sqlalchemy[asyncio]" 
]

[tool.setuptools.packages.find]
where = ["src"]